import jsPDF from 'jspdf'

/**
 * Downloads a cover letter as a formatted PDF
 * @param {string} text - Cover letter text
 * @param {string} filename - Output filename
 */
export function downloadCoverLetterAsPDF(text, filename = 'cover-letter.pdf') {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })

  const PAGE_W = 210
  const PAGE_H = 297
  const MARGIN = 20
  const MAX_W = PAGE_W - MARGIN * 2
  let y = MARGIN + 10

  // Header bar
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, PAGE_W, 12, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(255, 255, 255)
  doc.text('COVER LETTER — Generated by CoverCraft AI', MARGIN, 8)
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), PAGE_W - MARGIN, 8, { align: 'right' })

  y = 28

  // Body text
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(30, 30, 50)

  // Clean markdown and split into paragraphs
  const cleaned = text
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .trim()

  const paragraphs = cleaned.split(/\n{2,}/)

  for (const para of paragraphs) {
    if (!para.trim()) continue

    const lines = doc.splitTextToSize(para.trim(), MAX_W)

    // Check if we need a new page
    const blockH = lines.length * 6.5
    if (y + blockH > PAGE_H - MARGIN) {
      doc.addPage()
      y = MARGIN
    }

    doc.text(lines, MARGIN, y)
    y += blockH + 5
  }

  // Footer
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(7.5)
  doc.setTextColor(150, 150, 180)
  doc.text('Created with CoverCraft AI · covercraftai.vercel.app', PAGE_W / 2, PAGE_H - 8, { align: 'center' })

  doc.save(filename)
}

/**
 * Copies text to clipboard
 */
export async function copyToClipboard(text) {
  await navigator.clipboard.writeText(text)
}
